"""Roadmap model for learning path persistence."""

from datetime import datetime

from sqlalchemy import JSON, Boolean, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class Roadmap(Base):
    """Learning roadmap model.

    Represents a learning roadmap generated by the Planner Agent.
    Supports versioning through parent_roadmap_id and is_active flag.
    """

    __tablename__ = "roadmaps"

    id: Mapped[int] = mapped_column(primary_key=True)
    session_id: Mapped[str] = mapped_column(ForeignKey("sessions.id"))
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"))

    # Core content
    goal: Mapped[str] = mapped_column(String)
    milestones: Mapped[list] = mapped_column(JSON, default=list)
    mermaid: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Version control (support regeneration)
    version: Mapped[int] = mapped_column(Integer, default=1)
    parent_roadmap_id: Mapped[int | None] = mapped_column(ForeignKey("roadmaps.id"))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)

    # Standard timestamps
    created_at: Mapped[datetime] = mapped_column(default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(default=datetime.utcnow, onupdate=datetime.utcnow)
