"""add agent status tracking to sessions

Revision ID: 1048bbb829b4
Revises: unify_role_message_type
Create Date: 2026-02-13 17:19:26.239820

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1048bbb829b4'
down_revision: str | None = 'unify_role_message_type'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('agent_status', sa.String(), nullable=False, server_default='idle'))
    op.add_column('sessions', sa.Column('agent_started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'agent_started_at')
    op.drop_column('sessions', 'agent_status')
    # ### end Alembic commands ###
