"""Add roadmap relations to documents

Revision ID: 20250216_roadmap_relations
Revises: 7640d4dd0c42
Create Date: 2025-02-16 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20250216_roadmap_relations"
down_revision: str | None = "7640d4dd0c42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new columns to documents table
    # Note: Using nullable=True for existing records, then we could update them in a follow-up
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("roadmap_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("milestone_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("orphan_reason", sa.String(), nullable=True))
        batch_op.create_foreign_key(
            "fk_documents_roadmap_id",
            "roadmaps",
            ["roadmap_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove foreign key and columns
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_constraint("fk_documents_roadmap_id", type_="foreignkey")
        batch_op.drop_column("orphan_reason")
        batch_op.drop_column("milestone_id")
        batch_op.drop_column("roadmap_id")

    # ### end Alembic commands ###
