"""Add roadmap model

Revision ID: 7640d4dd0c42
Revises: 1048bbb829b4
Create Date: 2026-02-16 00:04:27.380705

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7640d4dd0c42"
down_revision: str | None = "1048bbb829b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roadmaps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("goal", sa.String(), nullable=False),
        sa.Column("milestones", sa.JSON(), nullable=False),
        sa.Column("mermaid", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_roadmap_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_roadmap_id"],
            ["roadmaps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # NOTE: The following entities table changes are commented out because:
    # 1. SQLite requires batch mode for operations that affect existing constraints
    # 2. These changes were planned for a separate migration
    # 3. They can be safely applied later when switching to PostgreSQL or using batch mode
    #
    # Original planned changes:
    # op.drop_index('unique_session_entity_name', table_name='entities')
    # op.create_unique_constraint('unique_session_entity_name', 'entities', ['session_id', 'name'])
    #
    # To apply these changes in the future, create a new migration with:
    # with op.batch_alter_table('entities') as batch_op:
    #     batch_op.drop_index('unique_session_entity_name')
    #     batch_op.create_unique_constraint('unique_session_entity_name', ['session_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: See upgrade() function for why entities table changes are commented out
    #
    # Original planned changes to revert:
    # op.drop_constraint('unique_session_entity_name', 'entities', type_='unique')
    # op.create_index('unique_session_entity_name', 'entities', ['session_id', 'name'], unique=1)
    #
    # When implementing the forward migration, also implement the corresponding rollback here.
    op.drop_table("roadmaps")
    # ### end Alembic commands ###
