"""Initial migration

Revision ID: af42447a0350
Revises: 
Create Date: 2026-02-12 20:52:21.334763

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'af42447a0350'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
